//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TwoDimBlocksData.proto
namespace TwoDimBlocks
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitData")]
  public partial class InitData : global::ProtoBuf.IExtensible
  {
    public InitData() {}
    
    private TwoDimBlocks.PlayerSyncData _sync;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TwoDimBlocks.PlayerSyncData sync
    {
      get { return _sync; }
      set { _sync = value; }
    }
    private TwoDimBlocks.BMPInitData _bmps;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bmps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TwoDimBlocks.BMPInitData bmps
    {
      get { return _bmps; }
      set { _bmps = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncData")]
  public partial class PlayerSyncData : global::ProtoBuf.IExtensible
  {
    public PlayerSyncData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private float _xpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _anime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"anime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anime
    {
      get { return _anime; }
      set { _anime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BMPInitData")]
  public partial class BMPInitData : global::ProtoBuf.IExtensible
  {
    public BMPInitData() {}
    
    private readonly global::System.Collections.Generic.List<int> _botbmp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"botbmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> botbmp
    {
      get { return _botbmp; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _frontbmp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frontbmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> frontbmp
    {
      get { return _frontbmp; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushData")]
  public partial class PushData : global::ProtoBuf.IExtensible
  {
    public PushData() {}
    
    private float _xpos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _anime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"anime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anime
    {
      get { return _anime; }
      set { _anime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PixelData")]
  public partial class PixelData : global::ProtoBuf.IExtensible
  {
    public PixelData() {}
    
    private bool _isbot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isbot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isbot
    {
      get { return _isbot; }
      set { _isbot = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _color;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawData")]
  public partial class DrawData : global::ProtoBuf.IExtensible
  {
    public DrawData() {}
    
    private readonly global::System.Collections.Generic.List<TwoDimBlocks.PixelData> _pixels = new global::System.Collections.Generic.List<TwoDimBlocks.PixelData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pixels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TwoDimBlocks.PixelData> pixels
    {
      get { return _pixels; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SnapShotData")]
  public partial class SnapShotData : global::ProtoBuf.IExtensible
  {
    public SnapShotData() {}
    
    private readonly global::System.Collections.Generic.List<TwoDimBlocks.PlayerSyncData> _syncs = new global::System.Collections.Generic.List<TwoDimBlocks.PlayerSyncData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"syncs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TwoDimBlocks.PlayerSyncData> syncs
    {
      get { return _syncs; }
    }
  
    private readonly global::System.Collections.Generic.List<TwoDimBlocks.PixelData> _pixels = new global::System.Collections.Generic.List<TwoDimBlocks.PixelData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pixels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TwoDimBlocks.PixelData> pixels
    {
      get { return _pixels; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}